import type { ICategories } from "~/typings/Categories"
import type { IDifficulties } from "~/typings/Difficulties"
import type { IModes } from "~/typings/Modes"
import type { ITags } from "~/typings/Tags"
import type { ITask } from "~/typings/Tasks"

export const categories:ICategories = {
  misc: "Sex and miscellaneous",
  oral: "Oral",
  public: "Public (Outside your house, somewhere people could be)",
  group: "Group sex",
  hotwife: "Hotwife",
  swinging: "Swinging",
  anal: "Anal",
  orgasms: "Orgasms",
  multiPen: "Multi penetration",
  photos: "Photos/Videos (You or someone took this photo/video of you)",
  cum: "Cum",
  sizeQueen: "Size Queen",
  positions: "Positions",
  places: "Places",
  toys: "Toys",
  clothing: "Clothing (At least one person saw you in this outfit)",
  bdsm: "BDSM",
  bodycount: "Bodycount",
  typeOfPeople: "Type of people",
  collection: "Collection (Things you still have in your possession)",
  exposition: "Exposition (Photos you have sent to men other than your boyfriend)"
}

export const modes:IModes = {
  monogamous: {name: "Monogamous relationship", level: 1},
  swinger: {name: "Swinger/sharing", level: 2},
  single: {name: "Single", level: 3}
}

export const tags:ITags = {
  public: "Public",
  bi: "Bisexual",
  exposition: "Exposition",
  hotwife: "Hotwife",
  cuckquean: "Cuckquean",
  anal: "Anal"
}

export const difficulties:IDifficulties = {
  easy: {name: "Easy", level: 1},
  medium: {name: "Medium", level: 2},
  hard: {name: "Hard", level: 3},
  extreme: {name: "Extreme", level: 4}
}

export const tasks:ITask[] = [
  // Misc
  {
    name: "Gave a striptease",
    points: 1,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Gave a boobjob",
    points: 1,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Gave a handjob",
    points: 1,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had sex",
    points: 1,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had sex 2 times in a day",
    points: 2,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had sex 3 times in a day",
    points: 3,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Had sex once a day for a week",
    points: 2,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had sex once a day for a month",
    points: 6,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Had sex while on your period",
    points: 2,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Sucked dick from a gloryhole",
    points: 2,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Fucked a dick from a gloryhole",
    points: 2,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Sucked a complete stranger at a gloryhole",
    points: 6,
    category: categories.misc,
    mode: modes.swinger.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fucked a complete stranger at a gloryhole",
    points: 8,
    category: categories.misc,
    mode: modes.swinger.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fucked for cash",
    points: 4,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Fucked a stranger for cash",
    points: 10,
    category: categories.misc,
    mode: modes.swinger.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Had drunken sex",
    points: 4,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had sex when you were passed out",
    points: 6,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Went back to your home without cleaning up",
    points: 4,
    category: categories.misc,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },


  // Oral
  {
    name: "Gave a blowjob",
    points: 1,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Licked balls",
    points: 1,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Made a guy cum only from blowjob",
    points: 2,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Gave a one hour long blowjob",
    points: 3,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Gave 2 blowjobs in a day",
    points: 3,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Gave a blowjob a day for a week",
    points: 4,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Gave a blowjob a day for one month",
    points: 6,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Deepthroated a dick",
    points: 2,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Held a deepthroat for 1 minute",
    points: 3,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Deepthroated a total time of 1 hour in a day",
    points: 4,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Gave analingus to someone",
    points: 3,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Gave analingus while inserting your tongue as far as possible",
    points: 4,
    category: categories.oral,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },

  // Anal
  {
    name: "Had anal sex",
    points: 2,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.anal]
  },
  {
    name: "Had anal sex twice in a day",
    points: 4,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.anal]
  },
  {
    name: "Had anal sex once a day for a week",
    points: 6,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.anal]
  },
  {
    name: "Took 2 dicks in the ass (Or dildos)",
    points: 8,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted buttplug",
    points: 2,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted buttplug for 1 hour",
    points: 3,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted buttplug for a whole day",
    points: 4,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted medium buttplug (2.5\" diameter or more)",
    points: 6,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted a large buttplug (3\" diameter or more)",
    points: 8,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted anal beads all the way",
    points: 4,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted medium anal beads (2\" diameter, 4 balls or more)",
    points: 6,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.anal]
  },
  {
    name: "Inserted large anal beads (2.5\" diameter, 5 balls or more)",
    points: 8,
    category: categories.anal,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.anal]
  },

  // Orgasms
  {
    name: "Had an orgasm",
    points: 1,
    category: categories.orgasms,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had an orgasm from anal",
    points: 4,
    category: categories.orgasms,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.anal]
  },
  {
    name: "Had an orgasm without stimulating pussy or ass",
    points: 6,
    category: categories.orgasms,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Had 5 orgasms in a session",
    points: 3,
    category: categories.orgasms,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had 10 orgasms in a day",
    points: 5,
    category: categories.orgasms,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Had 2 orgasms per day for a month",
    points: 4,
    category: categories.orgasms,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had 25 orgasms in a day",
    points: 8,
    category: categories.orgasms,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },

  // Multi penetration
  {
    name: "Had your mouth and pussy filled",
    points: 2,
    category: categories.multiPen,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had your mouth and ass filled",
    points: 3,
    category: categories.multiPen,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.anal]
  },
  {
    name: "Had your pussy and ass filled",
    points: 4,
    category: categories.multiPen,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.anal]
  },
  {
    name: "Had your mouth, pussy and ass filled",
    points: 6,
    category: categories.multiPen,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.anal]
  },
  {
    name: "Did double vaginal penetration",
    points: 8,
    category: categories.multiPen,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },

  // Public
  {
    name: "Went without underwear in public",
    points: 1,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.public]
  },
  {
    name: "Wore skimpy clothing without underwear in public",
    points: 2,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.public]
  },
  {
    name: "Flashed boobs in public",
    points: 2,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.public]
  },
  {
    name: "Flashed pussy in public",
    points: 2,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.public]
  },
  {
    name: "Wore semi transparent piece of clothing without underwear in public",
    points: 4,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.public]
  },
  {
    name: "Inserted buttplug in public",
    points: 4,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.public]
  },
  {
    name: "Gave blowjob in public",
    points: 4,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.public]
  },
  {
    name: "Had sex in public",
    points: 6,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.public]
  },
  {
    name: "Had an orgasm in public",
    points: 6,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.public]
  },
  {
    name: "Wore remote vibrator and got controlled in public",
    points: 5,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.public]
  },
  {
    name: "Had cum on your face in public",
    points: 8,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.public]
  },
  {
    name: "Ordered food while having cum in your mouth",
    points: 7,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.public]
  },
  {
    name: "Got completely naked in public",
    points: 10,
    category: categories.public,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.public]
  },

  // Photos/videos
  {
    name: "Photo of you in lingerie",
    points: 1,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Photo of your boobs",
    points: 1,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Photo of your pussy",
    points: 1,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Photo of your ass",
    points: 1,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "One finger challenge photo",
    points: 2,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Full nude",
    points: 3,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "On/off photo",
    points: 4,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Photo of creampie",
    points: 5,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Photo of facial",
    points: 5,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Photo of you being penetrated by someone",
    points: 6,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Pornception type photo",
    points: 7,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.public]
  },
  {
    name: "Masturbating video",
    points: 3,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Video of you having sex",
    points: 4,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Video of you receiving creampie",
    points: 5,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Video of you receiving facial",
    points: 5,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Boudoir photoshoot by a professional",
    points: 8,
    category: categories.photos,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },

  // Cum
  {
    name: "Got cum on your ass",
    points: 2,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got cum on your tits",
    points: 2,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got cum on your belly",
    points: 2,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got  cum on your feet",
    points: 2,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got cum on your face",
    points: 3,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got cum in your mouth",
    points: 3,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Swallowed cum",
    points: 4,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Swallowed 3 loads in a day",
    points: 6,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Swallowed 4 loads at once",
    points: 10,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Swallowed 2 loads per day for a week",
    points: 10,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Swallowed 2 loads per day for a month",
    points: 16,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Spread 1 load on yourself",
    points: 4,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got cum on your pussy",
    points: 3,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got creampied",
    points: 5,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Went back home with a creampie",
    points: 6,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Ate cum from a condom",
    points: 5,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Ate cum on food",
    points: 6,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Drank cum from glass",
    points: 7,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Played with cum in your mouth for 15 minutes",
    points: 6,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Spread cum on your face and let it dry",
    points: 8,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Wore cum filled panties for a day",
    points: 10,
    category: categories.cum,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },

  // Size queen
  {
    name: "Fully took a 7\"+ long dick/dildo",
    points: 3,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Fully took an 8\"+ long dick/dildo",
    points: 4,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Fully Took a 9\"+ long dick/dildo",
    points: 6,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fully took a 11\"+ long dick/dildo",
    points: 8,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Took a 6.5\"+ circumference dick/dildo",
    points: 2,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Took a 7.5\"+ circumference dick/dildo",
    points: 4,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Took a 8.5\"+ circumference dick/dildo",
    points: 6,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Fully deepthroated a 7\"+ dick/dildo",
    points: 2,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Fully deepthroated an 8\"+ dick/dildo",
    points: 4,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Fully deepthroated an 9\"+ dick/dildo",
    points: 6,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fully deepthroated an 11\"+ dick/dildo",
    points: 8,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Took 16+ inch anal snake",
    points: 10,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.anal]
  },
  {
    name: "Got fisted",
    points: 10,
    category: categories.sizeQueen,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },

  // Positions
  {
    name: "Missionary",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "69",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Doggy style",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Cowgirl/Reverse cowgirl",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Afternoon delight",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The visitor",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The slide",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The clasp",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The seated ball",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The curled angel",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The cross",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The perch",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The plough",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The fan",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The column",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The galley",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The sphinx",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The dolphin",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The lap top",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "The right angle",
    points: 1,
    category: categories.positions,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },

  // Places
  {
    name: "Bedroom",
    points: 1,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Bathroom",
    points: 1,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Living room",
    points: 1,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Kitchen",
    points: 1,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Public bathroom",
    points: 3,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Near a window",
    points: 2,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Hotel balcony",
    points: 3,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Park",
    points: 4,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Beach",
    points: 4,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Car",
    points: 2,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Forest",
    points: 3,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Abandoned building",
    points: 4,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Stairwell/corridor of hotel",
    points: 5,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Stranger/friend's house",
    points: 6,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Graveyard",
    points: 4,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Concert",
    points: 6,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Elevator",
    points: 6,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Cinema",
    points: 6,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Alley",
    points: 6,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Workplace",
    points: 7,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "In tent",
    points: 2,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Boat",
    points: 3,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Plane",
    points: 5,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Jacuzzi/pool",
    points: 2,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Swinger club",
    points: 6,
    category: categories.places,
    mode: modes.swinger.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Taxi",
    points: 8,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Library",
    points: 6,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Train/Bus",
    points: 6,
    category: categories.places,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },

  // Toys
  {
    name: "Dildo",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Realistic dildo",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Glass dildo",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Double dildo",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Vibrator",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Rabbit vibrator",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Egg vibrator",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Suction type vibrator",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Remote vibrator",
    points: 2,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Wand vibrator",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Buttplug",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Vibrating buttplug",
    points: 2,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Anal beads",
    points: 2,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Vibrating panties",
    points: 2,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Inflating dildo",
    points: 2,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Inflating buttplug",
    points: 2,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Sex swing",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Sex ramp",
    points: 1,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Household object",
    points: 2,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Fuck machine",
    points: 4,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Ride-on vibrator (MotorBunny)",
    points: 6,
    category: categories.toys,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },

  // Clothing
  {
    name: "Bra & string",
    points: 1,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Corset",
    points: 1,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Lingerie set/bodystocking",
    points: 1,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Rave apparel/Mini-dress in public",
    points: 1,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.public]
  },
  {
    name: "Teddies",
    points: 1,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Latex",
    points: 2,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Open cup/crotchless underwear",
    points: 2,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Candy underwear",
    points: 2,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Cosplay",
    points: 2,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Micro-bikini",
    points: 3,
    category: categories.clothing,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },

  // BDSM
  {
    name: "Had sex while tied up",
    points: 2,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had blindfolded sex",
    points: 1,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Been a slave for 2 hours",
    points: 3,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Been a slave for 1 day",
    points: 4,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Been a slave for 1 week",
    points: 6,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Been free use while tied up for 1 hour",
    points: 2,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Been free use while tied up for a day",
    points: 4,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Got spanked on the ass until red",
    points: 2,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got spanked on pussy at least 10 times",
    points: 2,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Got spanked until bleeding",
    points: 4,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Wore nipple clamps while having sex",
    points: 1,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Wore nipple clamps for a day",
    points: 3,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Got choked until almost passing out",
    points: 4,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Got peed on",
    points: 6,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Got tortured post-orgasm",
    points: 4,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Got verbally degraded",
    points: 1,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Roleplayed rape",
    points: 4,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Denied while in chastity for 1 day",
    points: 1,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Denied while in chastity for 3 days",
    points: 2,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Denied while in chastity for 1 week",
    points: 4,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Denied while in chastity for 1 month",
    points: 8,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Did wax play",
    points: 3,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Did ice play",
    points: 3,
    category: categories.bdsm,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },

  // Bodycount
  {
    name: "Had sex with 3+ different guys",
    points: 2,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Had sex with 10+ different guys",
    points: 4,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Had sex with 25+ different guys",
    points: 6,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Had sex with 50+ different guys",
    points: 8,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Had sex with 100+ different guys",
    points: 12,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Had sex with 2+ different guys the same day",
    points: 4,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Had sex with 3+ different guys the same day",
    points: 6,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Had sex with 5+ different guys the same day",
    points: 10,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Had sex with 5+ different guys in a week",
    points: 3,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Had sex with 15+ different guys in a month",
    points: 10,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Had sex with 30+ different guys in a month",
    points: 16,
    category: categories.bodycount,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },

  // Types of people
  {
    name: "Fucked a white",
    points: 1,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Fucked a black",
    points: 1,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Fucked an asian",
    points: 1,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Fucked an latino/latina",
    points: 1,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Fucked a man twice your age",
    points: 2,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "Fucked a man half your age",
    points: 3,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "Fucked a delivery man after ordering something",
    points: 4,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fucked a random man you did not choose",
    points: 6,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Let a friend choose a man for you",
    points: 6,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fucked a man that had a girlfriend",
    points: 6,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fucked a married man",
    points: 8,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "Fucked a stranger the first time you met him",
    points: 4,
    category: categories.typeOfPeople,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },

  // Collection (Things you still have in your possession)
  {
    name: "3+ sex toys",
    points: 1,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "6+ sex toys",
    points: 2,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "12+ sex toys",
    points: 3,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "25+ sex toys",
    points: 3,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "50+ sex toys",
    points: 4,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "100+ sex toys",
    points: 6,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "1+ clone-a-willy",
    points: 2,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "3+ different clone-a-willys",
    points: 4,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "10+ different clone-a-willys",
    points: 8,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "1+ dick pick",
    points: 1,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "10+ dick picks",
    points: 2,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "25+ dick picks",
    points: 4,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "50+ dick picks",
    points: 6,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "1+ photo having sex with a man",
    points: 1,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "3+ photos having sex with different men",
    points: 2,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "10+ photos having sex with different men",
    points: 4,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "25+ photos having sex with different men",
    points: 6,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "1+ video having sex with a man",
    points: 1,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "3+ videos having sex with different men",
    points: 2,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "10+ videos having sex with different men",
    points: 4,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "25+ videos having sex with different men",
    points: 6,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "1+ sex trophy from a man (Object taken from a hookup, often a piece of clothing)",
    points: 1,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
  },
  {
    name: "3+ sex trophies from different men",
    points: 2,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "10+ sex trophies from different men",
    points: 4,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "25+ sex trophies from different men",
    points: 6,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "1 used condom",
    points: 2,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
  },
  {
    name: "5+ used condoms",
    points: 4,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "10+ used condoms",
    points: 6,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "A photo of you wearing a used condom skirt",
    points: 12,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
  },
  {
    name: "A journal of all the men you had sex with",
    points: 6,
    category: categories.collection,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
  },

  // Exposition
  {
    name: "Sent a photo of you in lingerie to a stranger",
    points: 1,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of your boobs to a stranger",
    points: 1,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of your pussy to a stranger",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of your ass to a stranger",
    points: 1,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a one finger challenge photo to a stranger",
    points: 1,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a full nude photo to a stranger",
    points: 3,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of creampie to a stranger",
    points: 4,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of facial to a stranger",
    points: 5,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of you being penetrated to a stranger",
    points: 4,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.easy.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you masturbating to a stranger",
    points: 4,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you having sex to a stranger",
    points: 6,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you receiving creampie to a stranger",
    points: 7,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you receiving facial to a stranger",
    points: 8,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of you in lingerie online",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of your boobs online",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of your pussy online",
    points: 4,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of your ass online",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a one finger challenge photo online",
    points: 4,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a full nude photo online",
    points: 4,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of you being penetrated online",
    points: 6,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of creampie online",
    points: 6,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.medium.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of facial online",
    points: 10,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a video of you masturbating online",
    points: 8,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Uplaoded a video of you having sex online",
    points: 12,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a video of you receiving creampie online",
    points: 14,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a video of you receiving facial online",
    points: 16,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },

  {
    name: "Sent a photo of you in lingerie to a stranger (Face visible)",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of your boobs to a stranger (Face visible)",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of your pussy to a stranger (Face visible)",
    points: 4,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of your ass to a stranger (Face visible)",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a one finger challenge photo to a stranger (Face visible)",
    points: 2,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a full nude photo to a stranger (Face visible)",
    points: 6,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of creampie to a stranger (Face visible)",
    points: 8,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of facial to a stranger (Face visible)",
    points: 10,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a photo of you being penetrated to a stranger (Face visible)",
    points: 8,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you masturbating to a stranger (Face visible)",
    points: 8,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you having sex to a stranger (Face visible)",
    points: 12,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you receiving creampie to a stranger (Face visible)",
    points: 14,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a video of you receiving facial to a stranger (Face visible)",
    points: 16,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of you in lingerie online (Face visible)",
    points: 6,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of your boobs online (Face visible)",
    points: 6,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of your pussy online (Face visible)",
    points: 10,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of your ass online (Face visible)",
    points: 6,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a one finger challenge photo online (Face visible)",
    points: 10,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a full nude photo online (Face visible)",
    points: 10,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of you being penetrated online (Face visible)",
    points: 14,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of creampie online (Face visible)",
    points: 14,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a photo of facial online (Face visible)",
    points: 20,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a video of you masturbating online (Face visible)",
    points: 18,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uplaoded a video of you having sex online (Face visible)",
    points: 24,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a video of you receiving creampie online (Face visible)",
    points: 30,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a video of you receiving facial online (Face visible)",
    points: 32,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.extreme.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a sexy photo of yourself in lingerie on your most used social media",
    points: 16,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Sent a boudoir album to a stranger",
    points: 8,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },
  {
    name: "Uploaded a boudoir album online",
    points: 16,
    category: categories.exposition,
    mode: modes.monogamous.level,
    difficulty: difficulties.hard.level,
    tags: [tags.exposition]
  },


  // Group sex
  {
    name: "Fucked 2+ guys at the same time",
    points: 2,
    category: categories.group,
    mode: modes.single.level,
    difficulty: difficulties.medium.level
  },
  {
    name: "Got every hole filled",
    points: 3,
    category: categories.group,
    mode: modes.single.level,
    difficulty: difficulties.hard.level,
  },
  {
    name: "Fucked 10+ guys at once",
    points: 10,
    category: categories.group,
    mode: modes.single.level,
    difficulty: difficulties.extreme.level,
  },

  // Hotwife/Sharing
  {
    name: "Went to gloryhole with husband",
    points: 2,
    category: categories.hotwife,
    mode: modes.swinger.level,
    difficulty: difficulties.easy.level,
  },

  // Swinging
  {
    name: "Gave handjob to another man",
    points: 2,
    category: categories.swinging,
    mode: modes.swinger.level,
    difficulty: difficulties.easy.level,
  },
]