# Deploys on github pages when push to main
name: (Prod) Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set-up Node
      uses: actions/setup-node@v1
      with:
        node-version: "20.x"
    - run: npm install
    - run: npm run generate
    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        touch ./dist/.nojekyll
        npx gh-pages -d dist -t true -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}